### ISSUE TITLE
PunkAPI V2

### ISSUE THREAD

**Issue by samjbmason** [apfohl/punkapi#1]
Hi apfohl,

I have rewritten PunkAPI to make it faster, smaller in size and split into easier to manage chunks. Im looking at releasing it on **18th December**.  I have decided that as of the 18th December, v1 of the api will no longer work due to some unavoidable changes in the codebase. 

So what does this mean for you? There a few key things that will need to be updated in your lib, 

- The root endpoint has changed to `https://api.punkapi.com/`
- There is no longer any authentication on the app and will be relying on rate limits

Let me know if you need any help or clarification with anything, everything else is the same

Thanks
Sam

**Comment by apfohl** [comment]
Hi, thanks for the information. Do you have ani API documentation for the new API by now? Is it possible to use the new API right now, to test the application against it?

**Comment by samjbmason** [comment]
The new api can be found here https://punkapi-server-yvudxdwnze.now.sh/beers/random (not the final url obviously)

And some preliminary docs can be found here: https://punkapi-site-mspadgyyyl.now.sh/

**Comment by samjbmason** [comment]
Quick update about this, I have just been toying around with building  a proxy to keep the v1 api alive for a little bit longer and give people chance to migrate across, without breaking current apps.

Therefore, the official launch date of V2 of the api will still be the **18th December**, but I will also be keeping open v1 of the api until **15th Feburary 2017**.

Due to this I will also update the root endpoint which will now be `https://api.punkapi.com/v2`, here is an updated url which has these changes applied: https://punkapi-server-ivfgmegqyw.now.sh

**Comment by apfohl** [comment]
Thank, that'll be a big help.

**Comment by samjbmason** [comment]
Hi there, was just wondering if you had gotten anywhere with this, as I will be turning off V1 tonight at 11:59pm GMT 👍

**Comment by apfohl** [comment]
Sorry, had no time for this the last months. But will adopt the new API soon.

**Comment by apfohl** [comment]
I have some time now to finally do this. But before I implement this I want to finish the work on a new string library which I want to use for this project. This will help to make the development of new features way easier.

**Comment by apfohl** [comment]
Finally! 🍺
